name: Playwright UI Tests
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
  
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps --only-shell

    - name: Run Playwright tests
      env:
        BASE_URL: ${{ vars.BASE_URL }}
      run: npx playwright test

    - name: Upload Playwright artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: output/playwright-report/
        retention-days: 30

  dependabot:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      needs.test.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Check GitHub CLI version
        run: gh --version

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
