name: PR Workflow
on:
  pull_request:
    branches:
      - [ $default-branch ]

jobs:
  dependabot:
    name: Auto merge dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run Dependabot
        run: npx npm-check-updates -u && npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
